name: Keepalive

permissions:
  actions: write

on:
  schedule:
    - cron: '0 0 1 * *'  # runs on the 1st of every month (~every 30 days)

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
