name: Weekly Prez Bot

on:
  schedule:
    # Monday 08:00 UTC (≈09:00 Paris in winter, ≈10:00 in summer)
    - cron: "0 8 * * 1"
    - cron: "*/5 * * * *"  # TEMP: every 5 minutes
  workflow_dispatch:
    inputs:
      PARSE_DUMP_ONLY:
        description: "Dump all parsed tables and exit (no Slack)?"
        required: false
        default: "false"
      TEST_TODAY_ONLY:
        description: "Limit selection to today's date? (true/false)"
        required: false
        default: "false"
      FORCE_DATE:
        description: "Force local date (YYYY-MM-DD) for testing"
        required: false
        default: ""
      DEBUG_LOG:
        description: "Verbose parse diagnostics and JSON artifact?"
        required: false
        default: "false"

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      CONFLUENCE_BASE_URL:  ${{ secrets.CONFLUENCE_BASE_URL }}
      CONFLUENCE_PAGE_ID:   ${{ secrets.CONFLUENCE_PAGE_ID }}
      CONFLUENCE_USER:      ${{ secrets.CONFLUENCE_USER }}
      CONFLUENCE_API_TOKEN: ${{ secrets.CONFLUENCE_API_TOKEN }}
      SLACK_BOT_TOKEN:      ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL_ID:     ${{ secrets.SLACK_CHANNEL_ID }}
      CONFIG_PATH:          config.yaml

      # Inputs (used when you click "Run workflow")
      PARSE_DUMP_ONLY: ${{ github.event.inputs.PARSE_DUMP_ONLY || 'false' }}
      TEST_TODAY_ONLY: ${{ github.event.inputs.TEST_TODAY_ONLY || 'false' }}
      FORCE_DATE:      ${{ github.event.inputs.FORCE_DATE || '' }}
      DEBUG_LOG:       ${{ github.event.inputs.DEBUG_LOG || 'false' }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Run bot
        run: python app.py

      # Debug/Artifacts
      - name: List /tmp
        if: always()
        run: ls -lah /tmp || true

      - name: Upload parse artifacts (if present)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: parse-artifacts
          path: |
            /tmp/confluence_tables_dump.json
            /tmp/presenter_parse_debug.json
          if-no-files-found: ignore
